spring.application.name=watchCar
jwt.secret=usersecret
jwt.expiration=3600000
spring.main.allow-bean-definition-overriding=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.datasource.url=jdbc:h2:mem:testdb  # Banco em memória
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password  # Defina uma senha (pode ser vazia)
spring.datasource.dialect=org.hibernate.dialect.H2Dialect
spring.datasource.platform=h2
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# H2 console
spring.h2.console.enabled=true

# Configurações JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Definir o script de inicialização
spring.datasource.initialization-mode=always
spring.datasource.schema=classpath:schema.sql
spring.datasource.data=classpath:data.sql


