spring.application.name=watchCar
jwt.secret=usersecret
jwt.expiration=3600000

spring.main.allow-bean-definition-overriding=true

# Configuração Oracle
spring.datasource.url=jdbc:oracle:thin:@localhost:1522/WATCHCAR
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=ads
spring.datasource.password=ads
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
 
# Dialeto do Oracle
spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect

# Configurações JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Desativa o H2 Console e banco em memória
spring.h2.console.enabled=false
spring.datasource.initialization-mode=never

# Mailjet SMTP Configuration
spring.mail.host=smtp.maileroo.com
spring.mail.port=587
spring.mail.username=cjl@783e2ebd8f289aac.maileroo.org
spring.mail.password=853c357e6dfae48640dc25eb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.from=cjl@783e2ebd8f289aac.maileroo.org


spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
